# Generated by Django 5.0.6 on 2024-06-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support_system.worker'),
        ),
    ]
